name: Docker Build and Push

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_PREFIX: nilorg

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service: 
          - { name: auto-refresh-server, image: wechat-auto-refresh-server }
          - { name: gateway, image: wechat-gateway }
          - { name: proxy, image: wechat-proxy }

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_PREFIX }}/${{ matrix.service.image }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=dev,enable={{is_default_branch}}
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,prefix={{branch}}-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./${{ matrix.service.name }}/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64

  docker-summary:
    runs-on: ubuntu-latest
    needs: docker-build
    if: always()
    
    steps:
    - name: Check build results
      run: |
        if [[ "${{ needs.docker-build.result }}" == "success" ]]; then
          echo "✅ All Docker images built successfully!"
          echo "Images available:"
          echo "- nilorg/wechat-auto-refresh-server"
          echo "- nilorg/wechat-gateway" 
          echo "- nilorg/wechat-proxy"
        else
          echo "❌ Some Docker builds failed"
          exit 1
        fi
